[workspace]
members = ["crates/ic-metrics", "crates/ic-metrics-wasm-inspect"]
default-members = ["crates/ic-metrics"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.85.0"
version = "0.5.3"
license = "MIT"
repository = "https://github.com/dragginzgame/ic-metrics"
authors = ["borovan <84897664+borovan@users.noreply.github.com>"]
description = "Allocation-free, dependency-free measurement arithmetic"

[workspace.dependencies]
ic-host-artifacts = { version = "0.12", default-features = false }
ic-host-fs = { version = "0.12", default-features = false }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
